### ISSUE TITLE
React example

### ISSUE THREAD

**Issue by jakemanger** [allotropia/zetajs#4]
Hi, great project! Would it be possible to see a react or preferably nextjs example for this? I have been quite stuck trying to adapt the existing examples.

**Comment by jakemanger** [comment]
Just to add to this.

Every implementation I've tried gets stuck at errors like
```
Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at zeta.js:1084:17
 ```
 for `Module.uno_init.then`
 
 Also, does the zeta.js npm function? There seems to be no examples of it being used.

**Comment by smehrbrodt** [comment]
Which of the examples did you try?

> Also, does the zeta.js npm package work? There seems to be no examples of it being used.

It is used in some of the examples in the `examples` folder. Check which one has `zetajs` in the `package.json`.

**Comment by jakemanger** [comment]
Hi @smehrbrodt. I have tried convertpdf, ping-monitor and vuejs3-ping-tool. Ideally, I'd just like to get the convertpdf example working. They all seem to use the zeta.js file itself instead of the package and refer to the local path of './zeta.js' or the soffice_base_url followed by './assets/vendor/zetajs/zeta.js'. 

I'm just completely lost on how you would run any of these examples in React. 

I've made attempts where I serve the scripts from the public folder with the headers and create an Soffice.js component like:
```
'use client'
import React, { useEffect, useState } from 'react';

export default function Soffice() {
  const [moduleLoaded, setModuleLoaded] = useState(false);
  const [fileInputDisabled, setFileInputDisabled] = useState(true);

  useEffect(() => {
    const canvas = document.getElementById('qtcanvas');

    const loadWasmAndScript = async () => {
      try {
        window.Module = {
          canvas,
          uno_scripts: ['/zeta.js', '/office_thread.js'],
          locateFile: (path, prefix) => {
            console.log('Locating file:', path);
            console.log('Prefix:', prefix);
            return `${prefix || '/'}${path}`;
          },
          onRuntimeInitialized: () => {
            console.log('WASM and runtime initialized.');
            setFileInputDisabled(false); // Enable file input once runtime is ready
          },
          print: (message) => console.log(message),
          printErr: (message) => console.error(message),
        };

        const script = document.createElement('script');
        script.src = '/soffice.js';
        script.onload = () => {
          console.log('soffice.js script loaded.');
          console.log('FS:', window.FS);
        };
        script.onerror = () => {
          console.error('Failed to load soffice.js');
        };
        document.body.appendChild(script);
      } catch (error) {
        console.error('Error loading resources:', error);
      }
    };

    if (!moduleLoaded) {
      loadWasmAndScript();
      setModuleLoaded(true);
    }
  }, [moduleLoaded]);

  const handleFileInput = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    setFileInputDisabled(true);

    try {
      const port = await window.Module.uno_main;
      console.log('Obtained port:', port);
      const fileName = file.name;
      const extension = fileName.split('.').pop() || '';
      const filePath = `/tmp/input.${extension}`;
      const outputPath = '/tmp/output';

      console.log('Writing file to:', filePath);
      const fileData = new Uint8Array(await file.arrayBuffer());
      window.FS.writeFile(filePath, fileData);

      console.log('Posting convert message to port:', { cmd: 'convert', name: fileName, from: filePath, to: outputPath });
      port.postMessage({ cmd: 'convert', name: fileName, from: filePath, to: outputPath });

      port.onmessage = (e) => {
        console.log('Received message:', e.data);
        switch (e.data.cmd) {
          case 'converted':
            try {
              const outputData = window.FS.readFile(outputPath);
              const blob = new Blob([outputData], { type: 'application/pdf' });
              const url = URL.createObjectURL(blob);
              const iframe = document.getElementById('frame');
              iframe.contentWindow.location.replace(url);

              const downloadCheckbox = document.getElementById('download');
              if (downloadCheckbox.checked) {
                const link = document.createElement('a');
                link.href = url;
                link.download = `${fileName}.pdf`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
              }

              URL.revokeObjectURL(url);
              window.FS.unlink(filePath);
              window.FS.unlink(outputPath);
              console.log('File conversion and handling completed.');
            } catch (error) {
              console.error('Error during file handling:', error);
            }
            setFileInputDisabled(false);
            break;

          case 'start':
            setFileInputDisabled(false);
            break;

          default:
            console.error('Unknown command:', e.data.cmd);
            setFileInputDisabled(false);
            break;
        }
      };
    } catch (error) {
      console.error('Error handling file input:', error);
      setFileInputDisabled(false);
    }
  };

  return (
    <div>
      <input
        type="file"
        id="input"
        disabled={fileInputDisabled}
        onChange={handleFileInput}
      />
      <label>
        <input type="checkbox" id="download" /> Download
      </label>
      <iframe
        id="frame"
        style={{
          height: '90vh',
          width: '100vw',
        }}
      ></iframe>
      <canvas id="qtcanvas" style={{ display: 'none' }}></canvas>
    </div>
  );
}
```

Everything in Module doesn't seem to be created properly. e.g. `uno_scripts: ['/zeta.js', '/office_thread.js'],`
seems to be totally ignored and I have to specify print and printErr to avoid those errors.
and I get these console messages/errors:
```
Locating file: soffice.wasm
Soffice.js:18 Prefix: http://localhost:3000/
Soffice.js:32 soffice.js script loaded.
Soffice.js:33 FS: {root: FSNode, mounts: Array(0), devices: {…}, streams: Array(0), nextInode: 17, …}ErrnoError: class extendsFSNode: class FSStream: class MAX_OPEN_FDS: 4096absolutePath: ƒ absolutePath()allocate: ƒ allocate(stream,offset,length)analyzePath: ƒ analyzePath(path,dontResolveLastLink)chdir: ƒ chdir(path)chmod: ƒ chmod(path,mode,dontFollow)chown: ƒ chown(path,uid,gid,dontFollow)chrdev_stream_ops: {open: ƒ, llseek: ƒ}close: ƒ close(stream)closeStream: ƒ closeStream(fd)create: ƒ create(path,mode)createDataFile: ƒ createDataFile(parent,name,data,canRead,canWrite,canOwn)createDefaultDevices: createDefaultDevices(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=> {…}createDefaultDirectories: ƒ createDefaultDirectories()createDevice: ƒ createDevice(parent,name,input,output)createFile: ƒ createFile(parent,name,properties,canRead,canWrite)createFolder: ƒ createFolder()createLazyFile: createLazyFile(parent,name,url,canRead,canWrite){class LazyUint8Array{constructor(){this.lengthKnown=false;this.chunks=[]}get(idx){if(idx>this.length-1||idx<0){return undefined}var chunkOffset=idx%this.chunkSize;var chunkNum=idx/this.chunkSize|0;return this.getter(chunkNum)[chunkOffset]}setDataGetter(getter){this.getter=getter}cacheLength(){var xhr=new XMLHttpRequest;xhr.open("HEAD",url,false);xhr.send(null);if(!(xhr.status>=200&&xhr.status<300||xhr.status===304))throw new Error("Couldn't load "+url+". Status: "+xhr.status);var datalength=Number(xhr.getResponseHeader("Content-length"));var header;var hasByteServing=(header=xhr.getResponseHeader("Accept-Ranges"))&&header==="bytes";var usesGzip=(header=xhr.getResponseHeader("Content-Encoding"))&&header==="gzip";var chunkSize=1024*1024;if(!hasByteServing)chunkSize=datalength;var doXHR=(from,to)=> {…}createLink: ƒ createLink()createNode: ƒ createNode(parent,name,mode,rdev)createPath: ƒ createPath(parent,path,canRead,canWrite)createPreloadedFile: (parent,name,url,canRead,canWrite,onload,onerror,dontCreateFile,canOwn,preFinish)=> {…}createSpecialDirectories: createSpecialDirectories(){FS.mkdir("/proc");var proc_self=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var node=FS.createNode(proc_self,"fd",16384|511,73);node.node_ops={lookup(parent,name){var fd=+name;var stream=FS.getStreamChecked(fd);var ret={parent:null,mount:{mountpoint:"fake"},node_ops:{readlink:()=> {…}createStandardStreams: ƒ createStandardStreams(input,output,error)createStream: ƒ createStream(stream,fd=-1)currentPath: "/"cwd: ()=>FS.currentPathdestroyNode: ƒ destroyNode(node)devices: {259: {…}, 1280: {…}, 1536: {…}, 16384: {…}, 16640: {…}}dupStream: ƒ dupStream(origStream,fd=-1)fchmod: ƒ fchmod(fd,mode)fchown: ƒ fchown(fd,uid,gid)filesystems: {MEMFS: {…}}findObject: ƒ findObject(path,dontResolveLastLink)flagsToPermissionString: ƒ flagsToPermissionString(flag)forceLoadFile: ƒ forceLoadFile(obj)ftruncate: ƒ ftruncate(fd,len)genericErrors: {44: ErrnoError}getDevice: dev=>FS.devices[dev]getMounts: ƒ getMounts(mount)getPath: ƒ getPath(node)getStream: fd=>FS.streams[fd]getStreamChecked: ƒ getStreamChecked(fd)hashAddNode: ƒ hashAddNode(node)hashName: ƒ hashName(parentid,name)hashRemoveNode: ƒ hashRemoveNode(node)ignorePermissions: trueinit: ƒ init(input,output,error)initialized: falseioctl: ƒ ioctl(stream,cmd,arg)isBlkdev: ƒ isBlkdev(mode)isChrdev: ƒ isChrdev(mode)isClosed: ƒ isClosed(stream)isDir: ƒ isDir(mode)isFIFO: ƒ isFIFO(mode)isFile: ƒ isFile(mode)isLink: ƒ isLink(mode)isMountpoint: ƒ isMountpoint(node)isRoot: ƒ isRoot(node)isSocket: ƒ isSocket(mode)joinPath: ƒ joinPath()lchmod: ƒ lchmod(path,mode)lchown: ƒ lchown(path,uid,gid)llseek: ƒ llseek(stream,offset,whence)lookup: ƒ lookup(parent,name)lookupNode: ƒ lookupNode(parent,name)lookupPath: lookupPath(path,opts={}){path=PATH_FS.resolve(path);if(!path)return{path:"",node:null};var defaults={follow_mount:true,recurse_count:0};opts=Object.assign(defaults,opts);if(opts.recurse_count>8){throw new FS.ErrnoError(32)}var parts=path.split("/").filter(p=> {…}lstat: ƒ lstat(path)major: dev=>dev>>8makedev: (ma,mi)=>ma<<8|mimayCreate: ƒ mayCreate(dir,name)mayDelete: ƒ mayDelete(dir,name,isdir)mayLookup: ƒ mayLookup(dir)mayOpen: ƒ mayOpen(node,flags)minor: dev=>dev&255mkdev: ƒ mkdev(path,mode,dev)mkdir: ƒ mkdir(path,mode)mkdirTree: ƒ mkdirTree(path,mode)mknod: ƒ mknod(path,mode,dev)mmap: ƒ mmap(stream,length,position,prot,flags)mmapAlloc: ƒ mmapAlloc()mount: ƒ mount(type,opts,mountpoint)mounts: []msync: ƒ msync(stream,buffer,offset,length,mmapFlags)nameTable: (4096) [empty × 48, FSNode, empty × 231, FSNode, empty × 9, FSNode, empty × 219, FSNode, empty × 344, FSNode, empty × 190, FSNode, empty × 177, FSNode, empty × 23, FSNode, empty × 171, FSNode, empty × 1008, FSNode, empty × 831, FSNode, empty × 14, FSNode, empty × 144, FSNode, empty × 123, FSNode, empty × 383, FSNode, empty × 166]nextInode: 17nextfd: ƒ nextfd()nodePermissions: ƒ nodePermissions(node,perms)open: ƒ open(path,flags,mode)quit: ƒ quit()read: ƒ read(stream,buffer,offset,length,position)readFile: ƒ readFile(path,opts={})readdir: ƒ readdir(path)readlink: ƒ readlink(path)registerDevice: ƒ registerDevice(dev,ops)rename: ƒ rename(old_path,new_path)rmdir: ƒ rmdir(path)root: FSNode {parent: FSNode, mount: {…}, mounted: null, id: 1, name: '/', …}standardizePath: ƒ standardizePath()stat: ƒ stat(path,dontFollow)staticInit: staticInit(){[44].forEach(code=> {…}streams: []symlink: ƒ symlink(oldpath,newpath)syncFSRequests: 0syncfs: syncfs(populate,callback){if(typeof populate=="function"){callback=populate;populate=false}FS.syncFSRequests++;if(FS.syncFSRequests>1){err(`warning: ${FS.syncFSRequests} FS.syncfs operations in flight at once, probably just doing extra work`)}var mounts=FS.getMounts(FS.root.mount);var completed=0;function doCallback(errCode){assert(FS.syncFSRequests>0);FS.syncFSRequests--;return callback(errCode)}function done(errCode){if(errCode){if(!done.errored){done.errored=true;return doCallback(errCode)}return}if(++completed>=mounts.length){doCallback(null)}}mounts.forEach(mount=> {…}truncate: ƒ truncate(path,len)unlink: ƒ unlink(path)unmount: unmount(mountpoint){var lookup=FS.lookupPath(mountpoint,{follow_mount:false});if(!FS.isMountpoint(lookup.node)){throw new FS.ErrnoError(28)}var node=lookup.node;var mount=node.mounted;var mounts=FS.getMounts(mount);Object.keys(FS.nameTable).forEach(hash=> {…}utime: ƒ utime(path,atime,mtime)write: ƒ write(stream,buffer,offset,length,position,canOwn)writeFile: ƒ writeFile(path,data,opts={})[[Prototype]]: Object
Soffice.js:26 Aborted(`Module.arguments` has been replaced by `arguments_` (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))
window.console.error @ app-index.js:35
console.error @ hydration-error-info.js:41
printErr @ Soffice.js:26
abort @ soffice.js:1
get @ VM2391 soffice.js:1
(anonymous) @ soffice.js:1
soffice.js:1 Uncaught RuntimeError: Aborted(`Module.arguments` has been replaced by `arguments_` (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))
    at abort (soffice.js:1:30130)
    at Object.get (VM2391 soffice.js:1:34038)
    at soffice.js:1:19408
abort @ soffice.js:1
get @ VM2391 soffice.js:1
(anonymous) @ soffice.js:1
Soffice.js:32 soffice.js script loaded.
Soffice.js:33 FS: {root: FSNode, mounts: Array(0), devices: {…}, streams: Array(0), nextInode: 17, …}
Soffice.js:17 Locating file: soffice.data.js.metadata
Soffice.js:18 Prefix: 
Soffice.js:26 Aborted(Assertion failed)
window.console.error @ app-index.js:35
console.error @ hydration-error-info.js:41
printErr @ Soffice.js:26
abort @ soffice.js:1
assert @ soffice.js:1
addRunDependency @ VM2391 soffice.js:1
runMetaWithFS @ VM2391 soffice.js:1
callRuntimeCallbacks @ VM2391 soffice.js:1
preRun @ soffice.js:1
run @ soffice.js:1
runCaller @ VM2391 soffice.js:1
removeRunDependency @ soffice.js:1
receiveInstance @ VM2391 soffice.js:1
receiveInstantiationResult @ VM2391 soffice.js:1
Promise.then
(anonymous) @ VM2391 soffice.js:1
Promise.then
instantiateAsync @ VM2391 soffice.js:1
createWasm @ VM2391 soffice.js:1
(anonymous) @ VM2391 soffice.js:1
soffice.js:1 Uncaught (in promise) RuntimeError: Aborted(Assertion failed)
    at abort (soffice.js:1:30130)
    at assert (soffice.js:1:24347)
    at Object.addRunDependency (VM2391 soffice.js:1:29053)
    at runMetaWithFS (VM2391 soffice.js:1:14740)
    at callRuntimeCallbacks (VM2391 soffice.js:1:47218)
    at preRun (soffice.js:1:27192)
    at run (soffice.js:1:368857)
    at runCaller (VM2391 soffice.js:1:367926)
    at removeRunDependency (soffice.js:1:29972)
    at receiveInstance (VM2391 soffice.js:1:32818)
    at receiveInstantiationResult (VM2391 soffice.js:1:33139)
abort @ soffice.js:1
assert @ soffice.js:1
addRunDependency @ VM2391 soffice.js:1
runMetaWithFS @ VM2391 soffice.js:1
callRuntimeCallbacks @ VM2391 soffice.js:1
preRun @ soffice.js:1
run @ soffice.js:1
runCaller @ VM2391 soffice.js:1
removeRunDependency @ soffice.js:1
receiveInstance @ VM2391 soffice.js:1
receiveInstantiationResult @ VM2391 soffice.js:1
Promise.then
(anonymous) @ VM2391 soffice.js:1
Promise.then
instantiateAsync @ VM2391 soffice.js:1
createWasm @ VM2391 soffice.js:1
(anonymous) @ VM2391 soffice.js:1
Soffice.js:17 Locating file: soffice.data
Soffice.js:18 Prefix: 
```

the final Aborted error comes from soffice.js at this line:

```
Module["addRunDependency"]("soffice.data.js.metadata");
```
despite soffice.data.js.metadata downloading in the network tab.

Any help would be very much appreciated.

**Comment by smehrbrodt** [comment]
So you tried that with the WASM files located on your local dev server? You could also use the CDN: https://cdn.zetaoffice.net/zetaoffice_latest/

Can you push your full project somewhere for testing?

**Comment by jakemanger** [comment]
Yes, I tried a local dev server and the CDN. Same result unfortunately. 

Sure! I should have a demo ready in the next couple of days

**Comment by jakemanger** [comment]
Hi @smehrbrodt, here's the full project: https://github.com/jakemanger/zetajs_react_example

**Comment by shubhendusaurabh** [comment]
@jakemanger I found that due to react useeffect rerenders `soffice.js` is loaded multiple times which causes `soffice.js:1 Uncaught (in promise) RuntimeError: Aborted(Assertion failed)` errors.

To fix this I added conditional loading for `soffice.js`

```js
        const scriptId = 'sofficeJsScript'
        const script = document.createElement('script');
        script.src = '/soffice.js';
        script.id = scriptId;

          script.onload = () => {
            console.log('soffice.js script loaded.');
            console.log('FS:', window.FS);
          };
          script.onerror = () => {
            console.error('Failed to load soffice.js');
          };
        if (!document.getElementById(scriptId))
          document.body.appendChild(script);
```

There are other errors logged but document conversion works.

**Comment by jakemanger** [comment]
@shubhendusaurabh thanks so much for looking into this! That's great you solved it. I'm planning on releasing an open source project that uses this soon so will link it if you like. Thanks for working on such a great library.

**Comment by shubhendusaurabh** [comment]
@jakemanger I am not associated with zetajs team. I was facing similar issue while integrating it in my nextjs project. :)

**Comment by kolAflash** [comment]
> @jakemanger I am not associated with zetajs team. I was facing similar issue while integrating it in my nextjs project. :)

@shubhendusaurabh  
Big thanks for helping! :+1:  
If you like to share your nextjs project, I'd be interested to see how you use ZetaJS :smiley:

I'm planning to [add a helper script for common tasks](https://github.com/allotropia/zetajs/issues/6) to ZetaJS. The [conditional loading wrapper](https://github.com/allotropia/zetajs/issues/4#issuecomment-2571751764) for `soffice.js` will probably fit in well there.

&nbsp;

@jakemanger  
> [...] I'm planning on releasing an open source project that uses this soon so will link it if you like.

I'm not sure if I understand the grammar of your message.

I already thought about linking your React example in the [zetajs/README.md](https://github.com/allotropia/zetajs/blob/main/README.md) :+1: :smiley:  
And please don't hesitate to share a link when you release your open source project. I may also add it to the `README.md`.

**Comment by jakemanger** [comment]
> @jakemanger I am not associated with zetajs team. I was facing similar issue while integrating it in my nextjs project. :)

Oh, haha well thanks for the help. Funny to think that two people were doing such a niche thing at the same time on the other side of the world
